displayName=BossKCRivalLookup
author=Oyama
support=https://github.com/ItMeansBigMountain/BossKCRivalLookup
description=BossKCRivalLookup RuneLite plugin.
tags=bosskcrivallookup,runelite,osrs
plugins=com.itmeansbigmountain.bosskcrivallookup.BossKcrivalLookupPlugin
